Add test with restart/down container
acompany-develop/QuickMPC pull request #149
Opened 2023-03-31 06:18 UTC by mdonaka

# Summary
Add test with restart/down container.

# Purpose
Automation of abnormal test

# Contents
- Add container_test
  - container up test
  - Various request test with container down
  - Various request test with container restart

# Testing Methods Performed

2023-04-03 08:26 UTC, come2ry requested changes

2023-04-03 08:26 UTC, come2ry commented on scripts/container_test/medium_test.sh
> +    docker-compose $COMPOSE_FILES_OPT down -v
```suggestion
    rm /tmp/QuickMPC && docker-compose $COMPOSE_FILES_OPT down -v
```

2023-04-03 08:26 UTC, come2ry commented on scripts/container_test/medium_test.sh
> +    docker-compose $COMPOSE_FILES_OPT up medium_container
```suggestion
    ln -s $(pwd)/../ /tmp/QuickMPC && docker-compose $COMPOSE_FILES_OPT up medium_container
```

2023-04-03 08:33 UTC, arukuka approved these changes
Thank you for your contribution!

2023-04-03 08:56 UTC, mdonaka commented on scripts/container_test/medium_test.sh
> +    docker-compose $COMPOSE_FILES_OPT down -v
Thanks for pointing that out!
Fixed (and added option `-f`) with 48d13a1ad4df2afbb8134fcbe01d4eb34718d119.

2023-04-04 06:34 UTC, mdonaka commented
It turns out that the test fails once every few dozen times.
This will probably be solved by introducing a retry policy in X.
Therefore, I would set the PR to "draft" until this is implemented.

This PR itself remains unchanged.

2023-04-04 08:25 UTC, come2ry commented
@mdonaka 
I think the following issues with this PR.
-Using DooD, we have to create `scripts/docker-compose.unit.yml`, which is not DRY and has a large maintenance cost.

I believe this issue is due to the difference in paths between host and medium_container due to DooD, which I think can be solved by stopping DooD and running the test code directly from host.

Is there something wrong with running tests directly from host?
If there is no problem, the `scripts/docker-compose.unit.yml`, `medium_test_container` and `scripts/container_test/Dockerfile` can be deleted, making it easier to maintain and understand The code will be easier to maintain and understand.

2023-04-04 10:06 UTC, mdonaka commented
@come2ry 
Thank you for your comment!
I had created a container based on the stereotype, but it seems that there is no problem in the form of direct execution from the host!
I will revise it in the form you suggested. Thank you very much!

2023-04-04 10:10 UTC, mdonaka commented
I opened the PR because we did not receive any notification if the PR was a draft.

2023-04-07 11:27 UTC, mdonaka commented
@come2ry 
I changed to run tests directly. Please review again!

2023-04-10 01:20 UTC, come2ry approved these changes
LGTM！

2023-04-10 05:28 UTC, merged