DELETE : division between two Shares
acompany-develop/QuickMPC pull request #157
Opened 2023-04-10 05:16 UTC by sakamoto-souta

# Summary
DELETE : division between two Shares
# Purpose
to delete division which is unused
# Contents
delete division and the parts which depend on division
# Testing Methods Performed
make test t=./computation_container p=medium

2023-04-10 10:52 UTC, KotaTakahashi9320 requested changes
Thank you for your contribution!
Please check comments.

2023-04-11 01:06 UTC, watason approved these changes
good job!

2023-04-11 03:38 UTC, sakamoto-souta commented on packages/server/computation_container/share/share.hpp
> +    */
[f9c5143](https://github.com/acompany-develop/QuickMPC/pull/157/commits/f9c5143aef5c56d983f7df56296187554d01111b)

2023-04-11 03:38 UTC, sakamoto-souta commented on packages/server/computation_container/optimizer/BUILD
[be87cdb](https://github.com/acompany-develop/QuickMPC/pull/157/commits/be87cdbbffaa38430f3cc13c963640874855f29a)

2023-04-11 04:49 UTC, KotaTakahashi9320 approved these changes
LGTM

2023-04-12 09:15 UTC, merged