add nesterov momentum
acompany-develop/QuickMPC pull request #23
Opened 2022-08-26 03:39 UTC by watason

# Summary
implimentation nesterov momentum
# Purpose

# Contents

# Testing Methods Performed

2022-08-26 10:15 UTC, come2ry commented on src/ComputationContainer/Optimizer/Momentum.hpp
> +                }
@watason 
Please remove the comment out.

2022-08-26 10:15 UTC, come2ry commented on src/ComputationContainer/Test/IntegrationTest/OptimizeTest.hpp
>      // opts.emplace_back(std::string("newton"), opt3);
@watason 
Is this comment necessary?

2022-08-26 10:18 UTC, come2ry commented on src/ComputationContainer/Optimizer/Momentum.hpp
> +                }
Same for line 46.

2022-08-26 10:20 UTC, come2ry commented
@watason 
Up to how many input sizes is this optimization function guaranteed to work?

2022-08-29 03:39 UTC, mdonaka approved these changes

2022-08-31 23:37 UTC, watason commented
@come2ry 
i'm not sure what you are talking about.
sgd does not depend data size,also nesterov does not.
it works as long as the data load correctly.

2022-09-01 00:48 UTC, come2ry commented
@watason 
It appears that the test of learning with this optimization function is only guaranteed to work with 5 input data.

Is there a guarantee that this optimization function will not cause errors or accuracy problems with, for example, 1,000,000 data inputs?

2022-09-01 01:56 UTC, come2ry commented
Okay, I understand.

2022-09-01 03:22 UTC, arukuka requested changes
Thank you for your contribution!  LGTM.

This is a quite minute thing, but there is a notational variation in the author of the commit.
Could you correct it if you don't mind?
Also, please register email address used to GitHub for showing icon. :bow:

2022-09-01 03:53 UTC, watason commented
@arukuka 
wtf
asap i change.
thanks!

2022-09-01 04:59 UTC, arukuka approved these changes
Thank you for your quick response!  
I will merge it.

2022-09-01 04:59 UTC, merged